services:

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - short_url_service_network

  short_url_service:
    image: short-url-service:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BASE_URL=http://localhost
      - FLASK_RUN_PORT=4000
      - FLASK_ENV=production
    ports:
      - 4000:4000
    networks:
      - short_url_service_network
    depends_on:
      - redis

networks:
  short_url_service_network:
