services:

  short_url_service:
    image: short-url-service:latest
    container_name: short_url_service_python
    restart: always
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - BASE_URL=http://localhost:4001
      - FLASK_RUN_PORT=4000
      - FLASK_ENV=production
    ports:
      - 4001:4000
